version: "3"
services:
  system:
    build:
      context: .
      dockerfile: Dockerfile.system
    image: system-image

  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: build-image
    depends_on:
      - system
  
  runner:
    build:
      context: .
      dockerfile: Dockerfile.run
    depends_on:
      - builder
    environment:
      PORT: ${PORT}
      TZ: ${TZ}
    ports:
      - "${PORT}:${PORT}"