version: '3.8'

services:
  frontend:
    build:
      context: ./react-frontend
    volumes:
      - frontend-build:/app/build
    command: ["true"]
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./spring-backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "3000:80"  # todo: extract port from url 
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    env_file:
      - ./react-frontend/.env


volumes:
  db-data:
  frontend-build:

networks:
  app-net:
    driver: bridge