version: '3.8'

services:
  frontend:
    build:
      context: ./react-frontend
    volumes:
      - frontend-build:/app/build
    command: ["true"]
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./spring-backend
    # env_file:
    #   - .env
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=db
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 2s
      retries: 10

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80" 
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    env_file:
      - ./react-frontend/.env


volumes:
  db-data:
  frontend-build:

networks:
  app-net:
    driver: bridge